### PR TITLE
Explicitly Mention Core Components

### PR DESCRIPTION
**Pull request by hdost**
* Update distributions
** Add references to the core receivers, processors, extensions,
  exporters.
* Add flag `include_core` to not use implicit mentions inclusion.
* Minor indentation and spacing edits

Relates to https://github.com/open-telemetry/opentelemetry-collector/issues/3927

Signed-off-by: Harold Dost <harolddost@gmail.com>

### CODE REVIEW

**Review by jpkrohling — APPROVED** [review]
LGTM, thank you for this PR!

**Review by alolita — APPROVED** [review]

**Review by Aneurysm9 — APPROVED** [review]

**Comment by hdost** [comment]
Maybe temporarily the requirement for GoReleaser can be changed? Either way https://github.com/hdost/testing-github-actions/pull/1/files << Might be a way that it could be changed for the future.

**Comment by jpkrohling** [comment]
> Maybe temporarily the requirement for GoReleaser can be changed?

Yes, the requirement is new and not fully tested :-) Given that there *is* a change to `.goreleaser`, it's correct that the "Check GoReleaser Configuration" workflow should be executed, no? If that was just part of a test and the actual PR won't have it, I'll disable this check permanently until we have something in place like your scratch branch.

**Comment by hdost** [comment]
> > Maybe temporarily the requirement for GoReleaser can be changed?
> 
> 
> 
> Yes, the requirement is new and not fully tested :-) Given that there *is* a change to `.goreleaser`, it's correct that the "Check GoReleaser Configuration" workflow should be executed, no? If that was just part of a test and the actual PR won't have it, I'll disable this check permanently until we have something in place like your scratch branch.

I'll remove it but i think you might have to trigger the workflows since I'm not a code owner

**Comment by jpkrohling** [comment]
> I'll remove it but i think you might have to trigger the workflows since I'm not a code owner

I removed the requirement, it should be fine to merge without triggering .goreleaser. It's optional because it takes a really long time (30m or so), which is not reasonable for changes not touching .goreleaser.

**Comment by hdost** [comment]
Ok I've reverted the PR back to the originally approved change https://github.com/open-telemetry/opentelemetry-collector-releases/pull/48#event-5787906982

**Review by jpkrohling — APPROVED** [review]

**Pull request merged**
