### PR TITLE
test: run linux package tests nightly against latest contrib main [new]

### LINKED ISSUE #659: Add nightly linux package tests
### Description
Create a nightly version of the linux package tests that use the latest snapshots of main branch of core and contrib distributions from the respective repos.

This is a follow-up to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34372

### PR DESCRIPTION
**Pull request by mowies**
Supersedes https://github.com/open-telemetry/opentelemetry-collector-releases/pull/760

Changes compared to the previously reverted PR:
- adapted the `base-release.yaml` to the changed gorelease setup for otelcol-contrib

Copied description from old PR:

This PR enables nightly testing of the otelcol-contrib linux packages based on the latest main branch version of otelcol-contrib built in https://github.com/open-telemetry/opentelemetry-collector-contrib.
This change was made possible by splitting the otelcol-contrib gorelease config into 2 separate files, one for building and one for packaging/archives/docker images/etc.
(The split goreleaser build is a goreleaser pro feature)

Using the split building approach was the only viable option to achieve this. I did lots of research on this, it was talked about in the Collector SIG meeting and I also [asked the GoReleaser folks for their help](https://github.com/goreleaser/goreleaser/issues/5234).

Consequences of this change:
- better testing
- slightly less maintainability of the goreleaser files and generator code for otelcol-contrib since they have special handling now

Fixes #659

### CODE REVIEW

**Comment by mowies** [comment]
I ran a successful test release on my fork. Workflow run links and test release below:
- [k8s](https://github.com/mowies/opentelemetry-collector-releases/actions/runs/12176161079)
- [OTLP](https://github.com/mowies/opentelemetry-collector-releases/actions/runs/12176161076)
- [Core](https://github.com/mowies/opentelemetry-collector-releases/actions/runs/12176161073)
- [Contrib](https://github.com/mowies/opentelemetry-collector-releases/actions/runs/12176161069)
- [Builder](https://github.com/mowies/opentelemetry-collector-releases/actions/runs/12176161078) (failed because of the missing `cmd/builder/` tag during testing but nothing changed there so I will work upstream)
- [Test release](https://github.com/mowies/opentelemetry-collector-releases/releases/tag/v0.115.0)

**Review by mx-psi — APPROVED** [review]

**Comment by mx-psi** [comment]
For my understanding I would like to know what parts were not testable without the pro key

**Comment by mowies** [comment]
We use quite a few pro-only features and I specifically made use of a new one in my PR: [Importing of prebuilt binaries](https://goreleaser.com/customization/prebuilt/). Specifically, I either build the otelcol-contrib from scratch or I download the prebuilt binary from the contrib repo and use it.

Other pro-only features we use (probably not a complete list):
- [Split and Merge](https://goreleaser.com/customization/partial/)
- [Windows MSI installers](https://goreleaser.com/customization/msi/)
- [Global hooks](https://goreleaser.com/customization/hooks/)
- [Monorepo support](https://goreleaser.com/customization/monorepo/)

**Comment by mowies** [comment]
In this case testing was much easier with a pro key to be able to actually run a close-to-reality version of the setup from start (pushing a tag) to finish (the actual github release).

**Comment by mowies** [comment]
after a bit of time in rebase-hell this PR should be ready again for merging 🚀

**Comment by mx-psi** [comment]
@TylerHelmuth @atoulme can you take a look at this?

**Review by mx-psi — APPROVED** [review]
Re-approving

**Review by MovieStoreGuy — APPROVED** [review]

**Comment by mowies** [comment]
i had to downgrade the package tests from ubuntu-latest (as of a few days ago 24.04) to 22.04 because of some issue that i can't figure out right now. i can file a separate issue for that, but i think it's mostly related to the container setup of the package tests

**Review by TylerHelmuth — APPROVED** [review]

**Comment by mx-psi** [comment]
@atoulme will merge after this release is done if there are no further comments

**Comment by mowies** [comment]
ok i manually reverted the previous rebase since https://github.com/open-telemetry/opentelemetry-collector-releases/pull/784 happened

**Pull request merged**
