### PR TITLE
Fix MSI release

### PR DESCRIPTION
**Pull request by pjanotti**
The wixl tool required to build the MSI package for Windows was only added to the CI workflows not to the release one.

This change restores the original MSI code from PR #560 and fixes the breaking issue with commit 9143b1e

The problem caused by the initial PR was reported at https://github.com/open-telemetry/opentelemetry-collector-releases/pull/560#issuecomment-2147343522

### CODE REVIEW

**Comment by jpkrohling** [comment]
@pjanotti, are you able to test this change on a repository under your account? If you give me permissions on your fork, I can add the license key as env var temporarily to it.

**Comment by pjanotti** [comment]
@jpkrohling I'll follow up on Slack via DM.

**Comment by pjanotti** [comment]
Release validated on my fork, thanks @jpkrohling. I disabled `docker` to avoid the pushing docker images since it was going to fail. Results: https://github.com/pjanotti/opentelemetry-collector-releases/releases

Key jobs:

* [Release Core prepare windows 386](https://github.com/pjanotti/opentelemetry-collector-releases/actions/runs/9424522417/job/25964890956) - [MSI](https://github.com/pjanotti/opentelemetry-collector-releases/actions/runs/9424522417/artifacts/1580959586)
* [Release Core prepare windows amd64](https://github.com/pjanotti/opentelemetry-collector-releases/actions/runs/9424522417/job/25964891095) - [MSI](https://github.com/pjanotti/opentelemetry-collector-releases/actions/runs/9424522417/artifacts/1580959980)
* [Release Contrib prepare windows 386](https://github.com/pjanotti/opentelemetry-collector-releases/actions/runs/9424522385/job/25964890981) - [MSI](https://github.com/pjanotti/opentelemetry-collector-releases/actions/runs/9424522385/artifacts/1580968377)
* [Release Contrib prepare windows amd64](https://github.com/pjanotti/opentelemetry-collector-releases/actions/runs/9424522385/job/25964891142) - [MSI](https://github.com/pjanotti/opentelemetry-collector-releases/actions/runs/9424522385/artifacts/1580969199)

**Review by jpkrohling — APPROVED** [review]

**Comment by jpkrohling** [comment]
@mx-psi, if you have ideas for further verification, please let us know. Otherwise, I'll merge this towards the middle of the week.

**Comment by mx-psi** [comment]
Nothing specific for this PR, feel free to merge if you think it is ready :)

**Comment by jpkrohling** [comment]
I'll port these changes to my own distributions repo and see how it goes!

**Pull request merged**
