### PR TITLE
Remove ballast extension

### PR DESCRIPTION
**Pull request by TylerHelmuth**
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/8343, following the plan from https://github.com/open-telemetry/opentelemetry-collector/pull/10671#pullrequestreview-2191977002

### CODE REVIEW

**Review by mx-psi — COMMENTED** [review]
Can we wait for at least 1-2 releases to see if anybody complains about the metric changing?

I would also want to remove most/all mentions to the ballast extension and related options that appear in this search: https://github.com/search?q=org%3Aopen-telemetry+ballast+-repo%3Aopen-telemetry%2Fopentelemetry-collector+-repo%3Aopen-telemetry%2Fotel-arrow-collector&type=code&p=1

**Comment by TylerHelmuth** [comment]
@mx-psi created https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34683 to handle contrib.  The references in operator and helm chart should stay.

**Comment by mx-psi** [comment]
Merged!

**Review by codeboten — COMMENTED** [review]
Should this be good to go after v0.108.0 is out or do we want this as part of that release?

**Comment by TylerHelmuth** [comment]
I feel comfortable with it going in v0.108.0.  It has been deprecated for 8 months and the helm chart has not been using it by default for almost 9 months.

**Review by mx-psi — APPROVED** [review]
LGTM, I was waiting for the search index on https://github.com/open-telemetry/opentelemetry-collector-releases/pull/607#pullrequestreview-2196012278 to be updated, looking at the updated results I think this is good to go.

The End User Survey shows only 3 respondents using the memory ballast so the impact should be minimal  https://github.com/open-telemetry/sig-end-user/blob/main/end-user-surveys/otel-collector/otel-collector-survey.csv

**Pull request merged**
