### PR TITLE
adding support for linux/pp64le arch

### PR DESCRIPTION
**Pull request by adilhusain-s**
*

### CODE REVIEW

**Review by jpkrohling — CHANGES_REQUESTED** [review]
I'm blocking the merge of this until we have this platform as part of the CI for core and contrib first.

**Comment by adilhusain-s** [comment]
since the PR of collector-core is already merged and collector-contrib is in progress, could we also start working on this PR?


[collector-core PR link](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12166#issuecomment-1179308493)
[collector-contrib PR link](https://github.com/open-telemetry/opentelemetry-collector/pull/5645#event-6953681715)

**Comment by adilhusain-s** [comment]
Please review and merge.

**Review by jpkrohling — APPROVED** [review]
I believe this is ready to be merged.

**Pull request merged**
