### PR TITLE
feat: use chmod flag during COPY

### PR DESCRIPTION
**Pull request by greut**
The extra `chmod` step can be carried out by Docker itself. It requires buildkit mode to be on, but it's the case when using buildx.

### CODE REVIEW

**Comment by jpkrohling** [comment]
Are you facing a specific problem leading to this change?

**Comment by greut** [comment]
Not at all, as I've been rebuilding it locally for #204, this bit got me surprised and felt it was an opportunity to remove a comment pointing to an _old_ issue, https://github.com/open-telemetry/opentelemetry-collector/issues/1317

**Review by jpkrohling — APPROVED** [review]

**Comment by jpkrohling** [comment]
Before merging, can you positively confirm that you built an image with this new Dockerfile and it worked as expected?

**Comment by greut** [comment]
I've pushed a _fake release_ over there from that branch + the related changes in goreleaser.

- https://github.com/greut/opentelemetry-collector-releases/pkgs/container/opentelemetry-collector-releases%2Fopentelemetry-collector
- https://github.com/greut/opentelemetry-collector-releases/pkgs/container/opentelemetry-collector-releases%2Fopentelemetry-collector-contrib

**Review by jpkrohling — APPROVED** [review]

**Comment by jpkrohling** [comment]
@open-telemetry/collector-maintainers, @open-telemetry/collector-contrib-maintainer, this has the potential to break the release, but I believe it will not. In the worst case, the binaries in the generated images won't have the execute flag, preventing the binary from running.

In any case, my message to the next person in line to perform the release (@dmitryax?): keep this issue in mind if anything fails during the release process.

**Pull request merged**
