### PR TITLE
Add AWS S3 Receiver to contrib distribution

### PR DESCRIPTION
**Pull request by adcharre**
Built successfully with ocb.

### CODE REVIEW

**Review by songy23 — APPROVED** [review]

**Review by shrutimantri — APPROVED** [review]

**Review by shrutimantri — COMMENTED** [review]
Isn't this receiver still in `development` phase?

**Comment by adcharre** [comment]
> Isn't this receiver still in `development` phase?

I've just raised a PR to move this to `alpha` and it was suggested to also raise a PR on this repo. 
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35809

**Review by atoulme — APPROVED** [review]

**Comment by songy23** [comment]
Please rebase

**Comment by adcharre** [comment]
> Please rebase

@songy23 - done

**Review by mx-psi — APPROVED** [review]

**Pull request merged**
