### PR TITLE
Update go to 1.22

### PR DESCRIPTION
**Pull request by mowies**
Fixes https://github.com/open-telemetry/opentelemetry-collector-releases/issues/471

### CODE REVIEW

**Review by mx-psi — COMMENTED** [review]
Looks like #572 removed `github.com/goreleaser/nfpm/v2`  but did not tidy the `go.mod` file.

**Comment by mowies** [comment]
Seem like it should be fine. Marking as ready for review :)

**Review by mx-psi — APPROVED** [review]
LGTM, could you file an issue about ensuring `go.mod` is tidy on CI?

**Comment by mowies** [comment]
I filed a new issue now: https://github.com/open-telemetry/opentelemetry-collector-releases/issues/601

**Pull request merged**
