### PR TITLE
Copy etc/os-release to final images to make vuln scanners to work

### LINKED ISSUE #175: etc/os-release is not copied to final image
GCP [container analysis services](https://cloud.google.com/container-analysis/docs/container-scanning-overview#linux-versions) which perform vulnerability scans of images used in conjunction with GKE uses `etc/os-release` to determine the OS of the image.

otel collector does use Alpine 3.11 which is a supported base image, but the specific file isn't copied into the final image so the service is unable to scan it.

Could you add this step (ideally to all otel images) so that they are able to be scanned?

### PR DESCRIPTION
**Pull request by iblancasa**
Signed-off-by: Israel Blancas <iblancasa@gmail.com>

Closes #175

### CODE REVIEW

**Comment by iblancasa** [comment]
I'm not sure if this is a pretty good idea since the final images are based on `scratch` and not on `alpine` as #175 says.
https://github.com/aquasecurity/trivy/issues/173#issuecomment-546673051

**Comment by jpkrohling** [comment]
That's a great point. Can you check how we can get the vulnerability scanners to give us a green checkmark? What do other projects with scratch images do?

**Comment by iblancasa** [comment]
I'll try to gather some ideas... but I usually saw people using `trivy fs` command to deal with this kind of situations

**Comment by piotrgwiazda** [comment]
How about having another image with "*-alpline" tag created that will be based on alpine rather than on FROM scratch? The user/consumer will be free to select the image to use.

**Comment by iblancasa** [comment]
@piotrgwiazda the only thing we'll add in that case, are the vulnerabilities from the base OS. I'm not sure if the ones from the execuables will be detected... since for go projects, usually those tools check the `go.mod` file.

**Comment by jpkrohling** [comment]
> How about having another image with "*-alpline" tag created that will be based on alpine rather than on FROM scratch? The user/consumer will be free to select the image to use.

This generates an extra load on our side, as we would have to support 2x the number of images we currently have. I'd argue that we should have a way to tell those tools that we only have a binary on the image, instead of an OS with other tools.

**Comment by iblancasa** [comment]
The ideal would be to check the source code from each repository... but since this can be slow, I can add a script that checks out the different repositories and checks for vulnerabilities.

What do you think?

**Comment by jpkrohling** [comment]
GitHub already provides that for us, it can scan our own code via CodeQL and will advise us in case a dependency has a known vulnerability. We need existing vulnerability scanners to accept our images as safe even though they can't detect the underlying OS (because we are using images from scratch).

**Comment by iblancasa** [comment]
I see. Is changing the base images an option? Otherwise I think there is not a fix for this issue.

**Comment by jpkrohling** [comment]
> Is changing the base images an option?

It might be an option if there's a good reason for that. So far, I see that vulnerability scanners cannot give us a green mark because we are using scratch images. This is not the same as saying we have vulnerabilities.

**Comment by iblancasa** [comment]
I know but... I think there are no many options, right?

**Comment by jpkrohling** [comment]
Is there anything in the docs for GCP's tool, or for Sysdig/Snyk/Aqua on how to mark our container as scratch? Perhaps a tag that we can add to the image itself?

**Comment by iblancasa** [comment]
I don't find anything like that. The only thing I found is the `--vuln-type` argument from `trivy`. For instance:
```sh
trivy i --vuln-type library otel/opentelemetry-collector:latest
```

**Comment by jpkrohling** [comment]
Alright, I think we did what was reasonable around this. Unless I'm missing something crucial, I believe those tools should provide a way to be told that an image is "from scratch" and should be marked as such.

**Comment by iblancasa** [comment]
Hmmm I was not able to find anything related.
I did a couple of experiments... and something seems to work, is to just create a dummy file (using touch). What do you think?

**Pull request closed without merging**
