### PR TITLE
add /bin/sh dependency

### LINKED ISSUE #244: RPM packages are missing a /bin/sh dependency
/bin/sh is required for the postinstall.sh and other scripts.

Adding a `Requires:` for all dependencies needed during install is a common standard.

### PR DESCRIPTION
**Pull request by shawnbutts**
Fixes #244

### CODE REVIEW

**Comment by jpkrohling** [comment]
This was looking promising, any reasons for closing the PR?

**Comment by shawnbutts** [comment]
The CLA and the private information requirement.

**Comment by elmerfud** [comment]
Seems a bit silly to require a personal address to submit a PR.

**Comment by jpkrohling** [comment]
I agree with you. We are in the process of changing that to have DCO as an alternative to CLA.

**Comment by shawnbutts** [comment]
In the meantime, maybe someone that has already signed the CLA can get this done.

**Pull request closed without merging**
