### PR TITLE
Update goreleaser to add latest tags

### PR DESCRIPTION
**Pull request by bogdandrutu**
Fix https://github.com/open-telemetry/opentelemetry-collector-releases/issues/73

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Review by jpkrohling — APPROVED** [review]
LGTM. I would have preferred to have the update as one commit and the changes related to "latest" as another, which would make it easier to spot potential problems, but I couldn't find anything wrong with the change.

**Review by codeboten — COMMENTED** [review]
nit: i would split the whitespace (and possibly the yaml upgrade, if it's not related) change out of this pr to make it easier to review.

any thoughts on how we can test this?

**Comment by bogdandrutu** [comment]
@codeboten the reason to upgrade was because of some bug in v2 (rendering the version). I will split that.

**Comment by bogdandrutu** [comment]
@jpkrohling @codeboten please review https://github.com/open-telemetry/opentelemetry-collector-releases/pull/221 first

**Pull request merged**
