### PR TITLE
* Add azuredataexplorerexporter in manifest (PR 12730)

### PR DESCRIPTION
**Pull request by ag-ramachandran**

### CODE REVIEW

**Comment by jpkrohling** [comment]
The build is currently failing. Please ping me again once you fix it.

**Comment by ag-ramachandran** [comment]
@jpkrohling , quick question. We had a new component released yesterday . 

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12730

In this PR we have 	the following line. Could the build be failing because of this ? Would you know if we have to wait for the 0.6.2 release for this PR to have a passing build.

github.com/open-telemetry/opentelemetry-collector-contrib/exporter/azuredataexplorerexporter v0.0.0-00010101000000-000000000000

**Comment by jpkrohling** [comment]
This is a common problem; take a look at recent similar PRs. There was one for the header setter extension that you could use as a reference.

**Comment by codeboten** [comment]
Looking at the header setter extension PR [here](https://github.com/open-telemetry/opentelemetry-collector-releases/pull/181) it looks like the best way to move this forward may be to wait until the next release to include it (once the contrib repo v0.62.0 release is out)

**Comment by jpkrohling** [comment]
Please rebase this, it should fix the CI issues.

**Comment by ag-ramachandran** [comment]
Thanks @jpkrohling rebased the changes with main.

**Review by codeboten — APPROVED** [review]

**Pull request merged**
